version: "3.9"
services:
  app:
    build:
      context: .
    container_name: windsor_app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: windsor_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: windsor_certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
